# Generated by Django 4.2.2 on 2023-07-04 03:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_gerencia_turmas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='equipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_gerencia_turmas.equipe'),
        ),
    ]
