# Generated by Django 4.2.2 on 2023-07-04 22:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_gerencia_turmas', '0002_alter_aluno_equipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipe',
            name='alunos',
            field=models.ManyToManyField(related_name='equipes', to=settings.AUTH_USER_MODEL),
        ),
    ]
