# Generated by Django 4.2.2 on 2023-07-04 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_gerencia_turmas', '0003_equipe_alunos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipe',
            name='alunos',
        ),
    ]
