# Generated by Django 4.2.2 on 2023-07-07 22:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_gerencia_turmas', '0004_remove_equipe_alunos'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipe',
            name='saldo_pontos',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='RealizacaoAtividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('realizada_com_sucesso', models.BooleanField(default=False)),
                ('atividade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_gerencia_turmas.atividade')),
                ('equipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_gerencia_turmas.equipe')),
            ],
        ),
    ]
